#! /usr/bin/env perl
# ABSTRACT: run Perl5 test programs as soon as they are modified or created
# PODNAME: autotest

use strict;
use warnings;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use App::autotest;

my $app = App::autotest->new();
exit( $app->run ? 0 : 1 );

=head1 SYNOPSIS

    autotest

=head1 DESCRIPTION

C<autotest> is a program that runs your test programs whenever you
change them. Using it you don't have to switch between your editor
and the shell since your tests are run automatically when you save
them. Think "Continuous Testing".

=head1 AUTHOR

Gregor Goldbach <glauschwuffel@nomaden.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2012 by Gregor Goldbach.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
